name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      max-parallel: 4
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Build on Windows
      run: |
        cd src
        nmake -f Makefile.msvc.x64.in
      if: matrix.os == 'windows-latest'
    - name: Build on non-Windows
      run: |
        ./configure --prefix=$PREFIX --with-charset=utf8
        make && make install
      if: matrix.os != 'windows-latest'
